### ISSUE TITLE
compatibility issues with .stl files

### ISSUE THREAD

**Issue by DelphineRoy** [LeClubSandwichStudio/MUR#5] opened 2020-03-30 21:16 UTC
Could not read the .stl files on my version of cura (4.1.0). They should be readable with any version. Couldn't open it with Windows' stl reader either, nor with sketchup. Windows 3D Builder returned the message "Couldn't load that. Error code: 0x80004005".

**Comment by LeSuedois** [comment] 2020-04-02 13:57
hmm we don't have problems with our stl files under fusion 360 and prusa slicer...
Many people with other softwares printed out files without problem. I think the problem is on your side, so I close this issue.
Please try with other software. Sketchup is marvelous for "big" stuff and architecture!

**Closed as completed by LeSuedois** 2020-04-02 13:57 UTC
